repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v1.5.2
    hooks:
      - id: gofmt
      - id: goimports
      - id: govet
