# fish completion for hydro
complete -c hydro -l beginner -d 'Enable beginner-friendly defaults'
complete -c hydro -l burp-export -r -d 'Write matched requests and responses to a Burp-compatible XML file'
complete -c hydro -l burp-host -r -d 'POST matched findings to a Burp Collaborator endpoint'
complete -c hydro -l concurrency -r -d 'Number of concurrent workers'
complete -c hydro -l filter-size -r -d 'Filter visible hits by response size range (min-max bytes)'
complete -c hydro -l follow-redirects -d 'Follow HTTP redirects (up to 5 hops)'
complete -c hydro -s h -d 'Show usage information'
complete -c hydro -l help -d 'Show usage information'
complete -c hydro -l match-status -r -d 'Comma-separated list of HTTP status codes to include in hits'
complete -c hydro -l method -r -d 'HTTP method to use for requests (GET, HEAD, POST)'
complete -c hydro -l no-baseline -d 'Disable the automatic baseline request used for similarity filtering'
complete -c hydro -l output -r -d 'Path to write output results'
complete -c hydro -l output-format -r -d 'Format for --output (jsonl)'
complete -c hydro -l pre-hook -r -d 'Shell command to run once before requests to fetch auth headers (stdout JSON)'
complete -c hydro -l profile -r -d 'Named execution profile to load'
complete -c hydro -l resume -r -d 'Path to a SQLite database for resuming and recording runs'
complete -c hydro -l run-id -r -d 'Override the deterministic run identifier used for persistence'
complete -c hydro -l show-similarity -d 'Include similarity scores in output (debug)'
complete -c hydro -l similarity-threshold -r -d 'Hide hits whose bodies are this similar to the baseline (0-1)'
complete -c hydro -l timeout -r -d 'Request timeout duration'
complete -c hydro -s u -r -d 'Target URL or template (required)'
complete -c hydro -s w -r -d 'Path to the wordlist file (required)'
